import { Candidate } from '../types/candidate.types';

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@email.com',
    phone: '+1 (555) 123-4567',
    location: 'New York, NY',
    position: 'Frontend Developer',
    interview: 'Frontend Developer Interview',
    status: 'completed',
    score: 85,
    appliedAt: '2025-01-15T10:00:00Z',
    completedAt: '2025-01-18T14:30:00Z',
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'michael.chen@email.com',
    phone: '+1 (555) 987-6543',
    location: 'San Francisco, CA',
    position: 'Senior Backend Engineer',
    interview: 'Senior Backend Engineer',
    status: 'pending',
    score: null,
    appliedAt: '2025-01-20T09:00:00Z',
    completedAt: null,
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@email.com',
    phone: '+1 (555) 456-7890',
    location: 'Austin, TX',
    position: 'Product Manager',
    interview: 'Product Manager Assessment',
    status: 'completed',
    score: 92,
    appliedAt: '2025-01-12T11:00:00Z',
    completedAt: '2025-01-14T16:20:00Z',
  },
  {
    id: '4',
    name: 'David Kim',
    email: 'david.kim@email.com',
    phone: '+1 (555) 321-0987',
    location: 'Seattle, WA',
    position: 'Frontend Developer',
    interview: 'Frontend Developer Interview',
    status: 'in_progress',
    score: null,
    appliedAt: '2025-01-19T13:00:00Z',
    completedAt: null,
  },
  {
    id: '5',
    name: 'Jessica Martinez',
    email: 'jessica.martinez@email.com',
    phone: '+1 (555) 234-5678',
    location: 'Boston, MA',
    position: 'Frontend Developer',
    interview: 'Frontend Developer Interview',
    status: 'completed',
    score: 78,
    appliedAt: '2025-01-10T08:00:00Z',
    completedAt: '2025-01-13T10:15:00Z',
  },
  {
    id: '6',
    name: 'Robert Taylor',
    email: 'robert.taylor@email.com',
    phone: '+1 (555) 876-5432',
    location: 'Chicago, IL',
    position: 'Senior Backend Engineer',
    interview: 'Senior Backend Engineer',
    status: 'in_progress',
    score: null,
    appliedAt: '2025-01-21T14:00:00Z',
    completedAt: null,
  },
];
