import { CommandHandler, ICommandHandler, EventBus } from '@nestjs/cqrs';
import { Inject } from '@nestjs/common';
import { CreateUserCommand } from './create-user.command';
import { User } from '../../../domain/aggregates/user.aggregate';
import type { IUserRepository } from '../../../domain/repositories/user.repository.interface';
import type { IRoleRepository } from '../../../domain/repositories/role.repository.interface';
import { Email } from '../../../domain/value-objects/email.vo';
import { FullName } from '../../../domain/value-objects/full-name.vo';
import { UserAlreadyExistsException } from '../../../domain/exceptions/user.exceptions';
import { USER_EVENT_TYPES } from '../../../domain/constants';
import type { IOutboxService } from '../../interfaces/outbox-service.interface';
import type { IUnitOfWork } from '../../interfaces/unit-of-work.interface';
import { LoggerService } from '../../../infrastructure/logger/logger.service';

/**
 * Create User Command Handler
 * Orchestrates user creation use case
 */
@CommandHandler(CreateUserCommand)
export class CreateUserHandler implements ICommandHandler<CreateUserCommand> {
  constructor(
    @Inject('IUserRepository')
    private readonly userRepository: IUserRepository,
    @Inject('IRoleRepository')
    private readonly roleRepository: IRoleRepository,
    private readonly eventBus: EventBus,
    @Inject('IOutboxService')
    private readonly outboxService: IOutboxService,
    @Inject('IUnitOfWork')
    private readonly unitOfWork: IUnitOfWork,
    private readonly logger: LoggerService,
  ) {}

  async execute(command: CreateUserCommand): Promise<User> {
    this.logger.info('Creating new user', {
      email: command.email,
      externalAuthId: command.externalAuthId,
      userId: command.userId,
    });

    // 1. Check if user already exists
    const existingUser = await this.userRepository.findByExternalAuthId(
      command.externalAuthId,
    );

    if (existingUser) {
      throw new UserAlreadyExistsException(command.email);
    }

    // Check by email too
    const existingByEmail = await this.userRepository.findByEmail(command.email);
    if (existingByEmail) {
      throw new UserAlreadyExistsException(command.email);
    }

    // 2. Create Value Objects
    const email = Email.create(command.email);
    const fullName = FullName.create(command.firstName, command.lastName);

    // 3. Create Aggregate (userId comes from command, generated by API Gateway)
    const user = User.create(
      command.userId,
      command.externalAuthId,
      email,
      fullName,
    );

    // 4. Atomic save: aggregate + outbox in same transaction
    const eventId = await this.unitOfWork.execute(async (tx) => {
      await this.userRepository.save(user, tx);
      return this.outboxService.saveEvent(
        USER_EVENT_TYPES.CREATED,
        {
          userId: user.id,
          externalAuthId: user.externalAuthId,
          email: user.email.value,
          firstName: user.fullName.firstName,
          lastName: user.fullName.lastName,
          status: user.status.value,
          role: user.role.toString(),
          createdAt: user.createdAt.toISOString(),
        },
        user.id,
        tx,
      );
    });

    // 5. After commit: publish domain events (internal)
    user.getUncommittedEvents().forEach(event => {
      this.eventBus.publish(event);
    });
    user.clearEvents();

    // 6. Schedule BullMQ job for Kafka publishing
    await this.outboxService.schedulePublishing([eventId]);

    this.logger.info('User created successfully', {
      userId: user.id,
      email: user.email.value,
      role: user.role.toString(),
      status: user.status.value,
    });

    return user;
  }
}
