/**
 * Create User Command
 * Represents the intent to create a new user
 */
export class CreateUserCommand {
  constructor(
    public readonly userId: string,           // Internal UUID (generated by API Gateway)
    public readonly externalAuthId: string,   // External auth provider ID
    public readonly email: string,
    public readonly firstName: string,
    public readonly lastName: string,
  ) {}
}
