// User Domain Events for Kafka messaging

/**
 * Base structure for all events (commands and integration events)
 */
export interface BaseEvent {
  eventId: string;
  eventType: string;
  timestamp: number; // Unix timestamp in milliseconds
  version: string;
  source: string; // 'api-gateway', 'user-service', etc.
}

// ============ COMMAND EVENTS (imperative - do this) ============
// Published TO user-commands topic
// Consumed BY User Service

/**
 * Command to create a new user
 */
export interface UserCreateCommand extends BaseEvent {
  eventType: 'user.create';
  payload: {
    userId: string;           // Internal UUID (generated by API Gateway)
    externalAuthId: string;   // External auth provider ID (Keycloak/Auth0/etc)
    email: string;
    firstName?: string;
    lastName?: string;
    password?: string;
    registrationMethod?: 'keycloak' | 'oauth' | 'email';
  };
}

/**
 * Command to update user profile
 */
export interface UserUpdateCommand extends BaseEvent {
  eventType: 'user.update';
  payload: {
    userId: string;
    firstName?: string;
    lastName?: string;
    avatarUrl?: string;
  };
}

/**
 * Command to delete user
 */
export interface UserDeleteCommand extends BaseEvent {
  eventType: 'user.delete';
  payload: {
    userId: string;
    deletedBy: 'admin' | 'user' | 'system';
  };
}

/**
 * Command to suspend user
 */
export interface UserSuspendCommand extends BaseEvent {
  eventType: 'user.suspend';
  payload: {
    userId: string;
    reason?: string;
  };
}

/**
 * Command to activate user
 */
export interface UserActivateCommand extends BaseEvent {
  eventType: 'user.activate';
  payload: {
    userId: string;
  };
}

/**
 * Command to assign role to user
 */
export interface UserAssignRoleCommand extends BaseEvent {
  eventType: 'user.assign_role';
  payload: {
    userId: string;
    roleName: string;
    assignedBy?: string;
  };
}

/**
 * Command to remove role from user
 */
export interface UserRemoveRoleCommand extends BaseEvent {
  eventType: 'user.remove_role';
  payload: {
    userId: string;
    roleName: string;
    removedBy?: string;
  };
}

// Union type for all user commands
export type UserCommand =
  | UserCreateCommand
  | UserUpdateCommand
  | UserDeleteCommand
  | UserSuspendCommand
  | UserActivateCommand
  | UserAssignRoleCommand
  | UserRemoveRoleCommand;

// ============ INTEGRATION EVENTS (past tense - this happened) ============
// Published TO user-events topic
// Consumed BY other services (Interview, Notification, etc.)

/**
 * User was created (integration event)
 */
export interface UserCreatedEvent extends BaseEvent {
  eventType: 'user.created';
  source: 'user-service';
  payload: {
    userId: string;
    externalAuthId: string;
    email: string;
    firstName: string;
    lastName: string;
    status: string;
    role: string;
    createdAt: string;
  };
}

/**
 * User was updated (integration event)
 */
export interface UserUpdatedEvent extends BaseEvent {
  eventType: 'user.updated';
  source: 'user-service';
  payload: {
    userId: string;
    externalAuthId: string;
    email: string;
    firstName: string;
    lastName: string;
    role: string;
    updatedAt: string;
  };
}

/**
 * User was deleted (integration event)
 */
export interface UserDeletedEvent extends BaseEvent {
  eventType: 'user.deleted';
  source: 'user-service';
  payload: {
    userId: string;
    externalAuthId: string;
    deletedBy: 'admin' | 'user' | 'system';
    deletedAt: string;
  };
}

/**
 * User was suspended (integration event)
 */
export interface UserSuspendedEvent extends BaseEvent {
  eventType: 'user.suspended';
  source: 'user-service';
  payload: {
    userId: string;
    externalAuthId: string;
    suspendedAt: string;
  };
}

/**
 * User was activated (integration event)
 */
export interface UserActivatedEvent extends BaseEvent {
  eventType: 'user.activated';
  source: 'user-service';
  payload: {
    userId: string;
    externalAuthId: string;
    activatedAt: string;
  };
}

/**
 * Role was assigned to user (integration event)
 */
export interface UserRoleAssignedEvent extends BaseEvent {
  eventType: 'user.role_assigned';
  source: 'user-service';
  payload: {
    userId: string;
    externalAuthId: string;
    roleName: string;
    assignedAt: string;
  };
}

/**
 * Role was removed from user (integration event)
 */
export interface UserRoleRemovedEvent extends BaseEvent {
  eventType: 'user.role_removed';
  source: 'user-service';
  payload: {
    userId: string;
    externalAuthId: string;
    roleName: string;
    removedAt: string;
  };
}

/**
 * User selected their role (integration event)
 * This is a one-time event when user chooses candidate or HR
 */
export interface UserRoleSelectedEvent extends BaseEvent {
  eventType: 'user.role-selected';
  source: 'user-service';
  payload: {
    userId: string;
    externalAuthId: string;
    email: string;
    role: 'candidate' | 'hr';
    selectedAt: string;
  };
}

// ============ AUTH EVENTS (for authentication flow) ============
// Published TO auth-events topic
// These are separate from user commands/events

export interface UserAuthenticatedEvent extends BaseEvent {
  eventType: 'user.authenticated';
  payload: {
    externalAuthId: string;  // Keycloak ID (external auth provider ID)
    email: string;
    firstName?: string;
    lastName?: string;
    authMethod: 'oauth2' | 'jwt_refresh';
    sessionId: string;
    ipAddress?: string;
    userAgent?: string;
  };
}

export interface UserLoggedOutEvent extends BaseEvent {
  eventType: 'user.logged_out';
  payload: {
    externalAuthId: string;  // Keycloak ID (external auth provider ID)
    sessionId: string;
    logoutReason: 'user_action' | 'token_expired' | 'admin_action';
  };
}

// Union type for all user integration events
export type UserIntegrationEvent =
  | UserCreatedEvent
  | UserUpdatedEvent
  | UserDeletedEvent
  | UserSuspendedEvent
  | UserActivatedEvent
  | UserRoleAssignedEvent
  | UserRoleRemovedEvent
  | UserRoleSelectedEvent;

// Union type for auth events
export type UserAuthEvent =
  | UserAuthenticatedEvent
  | UserLoggedOutEvent;

// ============ COMMAND FACTORIES (for API Gateway) ============
export class UserCommandFactory {
  static createUserCreate(
    userId: string,           // Internal UUID
    externalAuthId: string,   // Keycloak/Auth0 ID
    email: string,
    firstName?: string,
    lastName?: string,
    password?: string,
  ): UserCreateCommand {
    return {
      eventId: crypto.randomUUID(),
      eventType: 'user.create',
      timestamp: Date.now(),
      version: '1.0',
      source: 'api-gateway',
      payload: {
        userId,
        externalAuthId,
        email,
        firstName,
        lastName,
        password,
        registrationMethod: 'keycloak',
      },
    };
  }

  static createUserUpdate(
    userId: string,
    firstName?: string,
    lastName?: string,
    avatarUrl?: string,
  ): UserUpdateCommand {
    return {
      eventId: crypto.randomUUID(),
      eventType: 'user.update',
      timestamp: Date.now(),
      version: '1.0',
      source: 'api-gateway',
      payload: {
        userId,
        firstName,
        lastName,
        avatarUrl,
      },
    };
  }

  static createUserDelete(
    userId: string,
    deletedBy: 'admin' | 'user' | 'system' = 'admin',
  ): UserDeleteCommand {
    return {
      eventId: crypto.randomUUID(),
      eventType: 'user.delete',
      timestamp: Date.now(),
      version: '1.0',
      source: 'api-gateway',
      payload: {
        userId,
        deletedBy,
      },
    };
  }

  static createUserSuspend(
    userId: string,
    reason?: string,
  ): UserSuspendCommand {
    return {
      eventId: crypto.randomUUID(),
      eventType: 'user.suspend',
      timestamp: Date.now(),
      version: '1.0',
      source: 'api-gateway',
      payload: {
        userId,
        reason,
      },
    };
  }

  static createUserActivate(
    userId: string,
  ): UserActivateCommand {
    return {
      eventId: crypto.randomUUID(),
      eventType: 'user.activate',
      timestamp: Date.now(),
      version: '1.0',
      source: 'api-gateway',
      payload: {
        userId,
      },
    };
  }

  static createUserAssignRole(
    userId: string,
    roleName: string,
    assignedBy?: string,
  ): UserAssignRoleCommand {
    return {
      eventId: crypto.randomUUID(),
      eventType: 'user.assign_role',
      timestamp: Date.now(),
      version: '1.0',
      source: 'api-gateway',
      payload: {
        userId,
        roleName,
        assignedBy,
      },
    };
  }

  static createUserRemoveRole(
    userId: string,
    roleName: string,
    removedBy?: string,
  ): UserRemoveRoleCommand {
    return {
      eventId: crypto.randomUUID(),
      eventType: 'user.remove_role',
      timestamp: Date.now(),
      version: '1.0',
      source: 'api-gateway',
      payload: {
        userId,
        roleName,
        removedBy,
      },
    };
  }
}

// ============ AUTH EVENT FACTORIES ============
export class AuthEventFactory {
  static createUserAuthenticated(
    externalAuthId: string,
    email: string,
    sessionId: string,
    authData?: Partial<UserAuthenticatedEvent['payload']>
  ): UserAuthenticatedEvent {
    return {
      eventId: crypto.randomUUID(),
      eventType: 'user.authenticated',
      timestamp: Date.now(),
      version: '1.0',
      source: 'api-gateway',
      payload: {
        externalAuthId,
        email,
        sessionId,
        authMethod: 'oauth2',
        ...authData,
      },
    };
  }

  static createUserLoggedOut(
    externalAuthId: string,
    sessionId: string,
    logoutReason: UserLoggedOutEvent['payload']['logoutReason']
  ): UserLoggedOutEvent {
    return {
      eventId: crypto.randomUUID(),
      eventType: 'user.logged_out',
      timestamp: Date.now(),
      version: '1.0',
      source: 'api-gateway',
      payload: {
        externalAuthId,
        sessionId,
        logoutReason,
      },
    };
  }
}
