/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["HealthController_healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness check */
        get: operations["HealthController_readinessCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["HealthController_livenessCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/kafka": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kafka health check */
        get: operations["HealthController_kafkaHealthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List interview templates
         * @description Get paginated list of templates. HR sees only their templates, Admin sees all.
         */
        get: operations["TemplatesController_list"];
        put?: never;
        /**
         * Create interview template
         * @description Creates a new interview template (HR and Admin only)
         */
        post: operations["TemplatesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get template by ID
         * @description Retrieve a specific template with all questions
         */
        get: operations["TemplatesController_getOne"];
        /**
         * Update template
         * @description Update template title, description, or settings
         */
        put: operations["TemplatesController_update"];
        post?: never;
        /**
         * Delete template
         * @description Soft delete (archive) an interview template
         */
        delete: operations["TemplatesController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get template questions
         * @description Retrieve all questions for a template
         */
        get: operations["TemplatesController_getQuestions"];
        put?: never;
        /**
         * Add question to template
         * @description Add a new question to the interview template
         */
        post: operations["TemplatesController_addQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{id}/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove question from template
         * @description Delete a question from the interview template
         */
        delete: operations["TemplatesController_removeQuestion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Publish template
         * @description Change template status from draft to active
         */
        put: operations["TemplatesController_publish"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MetricsController_getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        InterviewSettingsDto: {
            /**
             * @description Total time limit for the interview in minutes
             * @example 60
             */
            totalTimeLimit: number;
            /**
             * @description Allow candidates to retake the interview
             * @example false
             */
            allowRetakes: boolean;
            /**
             * @description Show timer to candidates during interview
             * @example true
             */
            showTimer: boolean;
            /**
             * @description Randomize question order for each candidate
             * @example false
             */
            randomizeQuestions: boolean;
        };
        CreateTemplateDto: {
            /**
             * @description Interview template title
             * @example Senior Developer Interview
             */
            title: string;
            /**
             * @description Detailed description of the interview template
             * @example Comprehensive interview for senior backend developers with focus on system design and architecture
             */
            description: string;
            /** @description Interview settings (optional) */
            settings?: components["schemas"]["InterviewSettingsDto"];
        };
        TemplateListItemDto: {
            /**
             * @description Template UUID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Template title
             * @example Senior Developer Interview
             */
            title: string;
            /**
             * @description Template description
             * @example Comprehensive interview for senior developers
             */
            description: string;
            /**
             * @description Template status
             * @example active
             * @enum {string}
             */
            status: "draft" | "active" | "archived";
            /**
             * @description User ID who created this template
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            createdBy: string;
            /**
             * @description Total number of questions
             * @example 5
             */
            questionsCount: number;
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2024-11-05T22:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             * @example 2024-11-05T22:30:00Z
             */
            updatedAt: string;
        };
        PaginatedTemplatesResponseDto: {
            /** @description List of templates */
            items: components["schemas"]["TemplateListItemDto"][];
            /**
             * @description Total number of templates
             * @example 42
             */
            total: number;
            /**
             * @description Current page number
             * @example 1
             */
            page: number;
            /**
             * @description Items per page
             * @example 10
             */
            limit: number;
            /**
             * @description Total number of pages
             * @example 5
             */
            totalPages: number;
        };
        InterviewSettingsResponseDto: {
            /**
             * @description Total time limit in minutes
             * @example 60
             */
            totalTimeLimit: number;
            /**
             * @description Allow candidates to retake the interview
             * @example false
             */
            allowRetakes: boolean;
            /**
             * @description Show timer during interview
             * @example true
             */
            showTimer: boolean;
            /**
             * @description Randomize question order
             * @example false
             */
            randomizeQuestions: boolean;
        };
        QuestionResponseDto: {
            /**
             * @description Question UUID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Question text
             * @example Describe your experience with microservices
             */
            text: string;
            /**
             * @description Question type
             * @example video
             * @enum {string}
             */
            type: "video" | "text" | "multiple_choice";
            /**
             * @description Display order (1-based)
             * @example 1
             */
            order: number;
            /**
             * @description Time limit in seconds
             * @example 180
             */
            timeLimit: number;
            /**
             * @description Whether question is mandatory
             * @example true
             */
            required: boolean;
            /**
             * @description Optional hints for candidates
             * @example Focus on real-world examples
             */
            hints?: string;
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2024-11-05T22:00:00Z
             */
            createdAt: string;
        };
        TemplateResponseDto: {
            /**
             * @description Template UUID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Template title
             * @example Senior Developer Interview
             */
            title: string;
            /**
             * @description Template description
             * @example Comprehensive interview for senior developers
             */
            description: string;
            /**
             * @description Template status
             * @example active
             * @enum {string}
             */
            status: "draft" | "active" | "archived";
            /**
             * @description User ID who created this template
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            createdBy: string;
            /** @description Interview settings */
            settings: components["schemas"]["InterviewSettingsResponseDto"];
            /** @description List of questions */
            questions: components["schemas"]["QuestionResponseDto"][];
            /**
             * @description Total number of questions
             * @example 5
             */
            questionsCount: number;
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2024-11-05T22:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             * @example 2024-11-05T22:30:00Z
             */
            updatedAt: string;
        };
        AddQuestionDto: {
            /**
             * @description Question text
             * @example Describe your experience with microservices architecture and event-driven design patterns.
             */
            text: string;
            /**
             * @description Type of question response
             * @example video
             * @enum {string}
             */
            type: "video" | "text" | "multiple_choice";
            /**
             * @description Display order of the question (1-based)
             * @example 1
             */
            order: number;
            /**
             * @description Time limit for answering the question in seconds
             * @example 180
             */
            timeLimit: number;
            /**
             * @description Whether this question is mandatory
             * @example true
             */
            required: boolean;
            /**
             * @description Optional hints for the candidate
             * @example Focus on real-world examples from your previous projects
             */
            hints?: string;
        };
        UpdateTemplateDto: {
            /**
             * @description Updated interview template title
             * @example Senior Full-Stack Developer Interview
             */
            title?: string;
            /**
             * @description Updated detailed description
             * @example Updated comprehensive interview for senior full-stack developers
             */
            description?: string;
            /** @description Updated interview settings */
            settings?: components["schemas"]["InterviewSettingsDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_readinessCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_livenessCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_kafkaHealthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kafka connection status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TemplatesController_list: {
        parameters: {
            query?: {
                /** @description Filter by status */
                status?: "draft" | "active" | "archived";
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                limit?: number;
            };
            header: {
                "x-user-id": string;
                "x-user-role": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTemplatesResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TemplatesController_create: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
                "x-user-role": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateDto"];
            };
        };
        responses: {
            /** @description Template created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized - Invalid internal token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TemplatesController_getOne: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
                "x-user-role": string;
            };
            path: {
                /** @description Template ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponseDto"];
                };
            };
            /** @description Forbidden - Not the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TemplatesController_update: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
                "x-user-role": string;
            };
            path: {
                /** @description Template ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTemplateDto"];
            };
        };
        responses: {
            /** @description Template updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponseDto"];
                };
            };
            /** @description Forbidden - Not the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TemplatesController_delete: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
                "x-user-role": string;
            };
            path: {
                /** @description Template ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Not the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TemplatesController_getQuestions: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
                "x-user-role": string;
            };
            path: {
                /** @description Template ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of questions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        questions?: unknown[];
                    };
                };
            };
            /** @description Forbidden - Not the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TemplatesController_addQuestion: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
                "x-user-role": string;
            };
            path: {
                /** @description Template ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddQuestionDto"];
            };
        };
        responses: {
            /** @description Question added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                    };
                };
            };
            /** @description Forbidden - Not the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TemplatesController_removeQuestion: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
                "x-user-role": string;
            };
            path: {
                /** @description Template ID */
                id: string;
                /** @description Question ID */
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Question removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Not the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Template or question not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TemplatesController_publish: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
                "x-user-role": string;
            };
            path: {
                /** @description Template ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template published */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "active";
                    };
                };
            };
            /** @description Forbidden - Not the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetricsController_getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
